
services:

  zabbix-db:
    image: mysql:8.0
    container_name: "zabbix-db"
    restart: unless-stopped
    
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./zabbix-mysql.cnf:/etc/mysql/conf.d/zabbix-mysql.cnf
      - zabbix-db-data:/var/lib/mysql
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: "zabbix-server"
    restart: unless-stopped
    ports:
      - "${ZABBIX_SERVER_PORT}:10051"
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - zabbix-db
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: "zabbix-web"
    restart: unless-stopped
    ports:
      - "${ZABBIX_HTTP_PORT}:8080"
      - "${ZABBIX_HTTPS_PORT}:8443"
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network
  
networks:
  zabbix-network:
    driver: bridge

volumes:
  zabbix-db-data: