
services:

  zabbix-db:
    image: mysql:8.0
    container_name: "zabbix-db"
    restart: unless-stopped
    
    environment:
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      MYSQL_ROOT_PASSWORD: "zabbix"
    volumes:
      - ./zabbix-mysql.cnf:/etc/mysql/conf.d/zabbix-mysql.cnf
      - zabbix-db-data:/var/lib/mysql
    networks:
      - zabbix-network

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    container_name: "zabbix-server"
    restart: unless-stopped
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
    depends_on:
      - zabbix-db
    networks:
      - zabbix-network

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:latest
    container_name: "zabbix-web"
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_SERVER_HOST: "zabbix-db"
      MYSQL_DATABASE: "zabbix"
      MYSQL_USER: "zabbix"
      MYSQL_PASSWORD: "zabbix"
      ZBX_SERVER_HOST: "zabbix-server"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network
  
networks:
  zabbix-network:
    driver: bridge

volumes:
  zabbix-db-data: